Bump kotlin-stdlib-jdk8 from 1.8.10 to 1.8.20 (#14)
Bumps [kotlin-stdlib-jdk8](https://github.com/JetBrains/kotlin) from
1.8.10 to 1.8.20.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/JetBrains/kotlin/releases">kotlin-stdlib-jdk8's
releases</a>.</em></p>
<blockquote>
<h2>Kotlin 1.8.20-RC2</h2>
<h2>Changelog</h2>
<h3>Compiler</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-57388"><code>KT-57388</code></a>
Kapt+JVM_IR: &quot;RuntimeException: No type for expression&quot; for
delegated property</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-57242"><code>KT-57242</code></a>
Equals behaviour for value classes implementing interfaces is different
between 1.8.10 and 1.8.20-RC</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-57261"><code>KT-57261</code></a>
&quot;IllegalArgumentException was thrown at:
MemoizedInlineClassReplacements.getSpecializedEqualsMethod&quot; when
comparing non-inline class instance with an inline class instance</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-56527"><code>KT-56527</code></a>
K2: &quot;AssertionError: Assertion failed&quot; during compilation in
SequentialFilePositionFinder</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-57107"><code>KT-57107</code></a>
Handling of Windows line endings CRLF broken in latest snapshot with
K2</li>
</ul>
<h3>Tools. Gradle</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-57296"><code>KT-57296</code></a>
Build statistics sending errors in case of buildSrc directory usage with
kotlin-dsl plugin applied</li>
</ul>
<h3>Tools. Gradle. JS</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-57285"><code>KT-57285</code></a>
KJS / Gradle / MPP: FileNotFoundException on publishing empty KJS
sourceset</li>
</ul>
<h3>Tools. Gradle. Multiplatform</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-57460"><code>KT-57460</code></a>
Kotlin Gradle Plugin: Null <code>this</code> pointer in
transformCommonMainDependenciesMetadata</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-57306"><code>KT-57306</code></a>
[Kotlin 1.8.20-RC] GradleException: Could not load the value of field
<code>apiConfiguration</code> of
<code>org.jetbrains.kotlin.gradle.plugin.mpp.compilationImpl.DefaultKotlinCompilationConfigurationsContainer</code></li>
</ul>
<h2>Checksums</h2>
<table>
<thead>
<tr>
<th>File</th>
<th>Sha256</th>
</tr>
</thead>
<tbody>
<tr>
<td>kotlin-compiler-1.8.20-RC2.zip</td>

<td>0db23d86962bece7577c19b76ec6b27611e5c4b7c70e93d71451d289e6a7741b</td>
</tr>
<tr>
<td>kotlin-native-linux-x86_64-1.8.20-RC2.tar.gz</td>

<td>e38429bd0f778689c3953d4c3d5aa67c30fc9c39c0fa4d75463fa645356aa97b</td>
</tr>
<tr>
<td>kotlin-native-macos-x86_64-1.8.20-RC2.tar.gz</td>

<td>0939c73f2d30b0eaed826d2dd3eb6ce0a4720ccaa48a8fed2b9439b3168273ef</td>
</tr>
<tr>
<td>kotlin-native-macos-aarch64-1.8.20-RC2.tar.gz</td>

<td>536fb2d6f26d4f9ed351a07c8673fe3c8d669cedc983b6151ef1d36f8bd564b4</td>
</tr>
<tr>
<td>kotlin-native-windows-x86_64-1.8.20-RC2.zip</td>

<td>2fd80c2f59125469d17d35a79c7711302875f8dd4a0403d6e0885e678a099ece</td>
</tr>
</tbody>
</table>
<h2>Kotlin 1.8.20-RC</h2>
<h2>Changelog</h2>
<h3>Backend. Wasm</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-56584"><code>KT-56584</code></a>
K/Wasm: Can't link symbol class</li>
</ul>
<h3>Compiler</h3>
<h4>Fixes</h4>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-57053"><code>KT-57053</code></a>
Problem around anonymous objects in inline functions</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-56965"><code>KT-56965</code></a>
K/N: linkDebugFrameworkIosArm64 tasks failing with
UnsupportedOperationException: VAR name:disposables
type:com.badoo.reaktive.disposable.CompositeDisposable [val]</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-56815"><code>KT-56815</code></a>
compileKotlin task is stuck with while(true) and suspend function</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-56258"><code>KT-56258</code></a>
VerifyError: Bad local variable type when using -Xdebug</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a
href="https://github.com/JetBrains/kotlin/commits">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.jetbrains.kotlin:kotlin-stdlib-jdk8&package-manager=maven&previous-version=1.8.10&new-version=1.8.20)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>